name: opus_dart
version: 3.0.2
homepage: https://github.com/EPNW/opus_dart
description: Wraps libopus in dart, and additionally provides a dart friendly API for encoding and decoding
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  ffi: ^2.1.0
  web_ffi: ^0.7.1